name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: dotnet build AWS-NetCoreExample/src/AWS-NetCoreExample
    - name: Test
      run: dotnet test AWS-NetCoreExample/test/AWS-NetCoreExample.Tests
    - name: Install Amazon.Lambda.Tools
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: Deploy
      run: |
        cd AWS-NetCoreExample/src/AWS-NetCoreExample
        dotnet lambda package
        dotnet lambda deploy-function AWS-NetCoreExample --region eu-north-1 -frun dotnet6 --aws-access-key-id AKIAZXY2XUD5U4L2OR4V --aws-secret-key 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 --disable-interactive true
